version: '3'
services:
  ms-ilyas-betest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - dbs
      - redis_ilyas_betest
  dbs:
    image: mongo:latest
    container_name: database-ilyas-betest
    ports:
      - 27017:27017
    volumes:
      - database-ilyas-betest:/data/db
    networks:
      - app_network
  redis_ilyas_betest:
    image: "redis:latest"
    container_name: redis-ilyas-betest
    ports:
      - "6379:6379"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  database-ilyas-betest:
